[package]
name = "sofa"
version = "0.6.0"
authors = ["Mathieu Amiot <mathieu.amiot@yellowinnovation.fr>"]
license = "MIT/Apache-2.0"
description = "Sofa - CouchDB for Rust"
readme = "README.md"
documentation = "https://docs.rs/sofa"
homepage = "https://github.com/YellowInnovation/sofa"
repository = "https://github.com/YellowInnovation/sofa"
keywords = ["couchdb", "orm", "database", "nosql"]
categories = ["database"]
include = [
    "**/*.rs",
    "Cargo.toml"
]

[dependencies]
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"

[dev-dependencies]
pretty_assertions = "0.5"
